server:
  address: 0.0.0.0
  port: 23446
  shutdown: graceful

  ssl:
    enabled: true
    key-store: classpath:sslkey.p12
    key-store-password: 1234567890
    keyStoreType: PKCS12
    keyAlias: sshkeys

spring:
  application-dev.yml:
    name: Git-Remote-Repo-Listener
  main:
    web-application-type: reactive
    banner-mode: console
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  file:
    path: ./GitRemoteRepoAnalyzer-Logs

app:
  r2dbc:
    host: localhost
    port: 3306
    user: Jesse_EC233
    password: 3191955858_EC
    default-schema: git_remote_repo_analyzer

  redis:
    host: localhost
    port: 6379
    username: Jesse
    password: 1234567890

  id-consumer:
    global-id-key: "ids:buffer:global"
    blockTimeout: 1s
    retries: 3
    start-backoff: 100ms
    max-backoff: 500ms
    directory-urls:
      next: http://localhost:65533/api/id_allocator/next
      next-batch: http://localhost:65533/api/id_allocator/next-batch

  # 数据库的限流背压配置
  database-concurrent:
    # 限制仓库并发数
    max-repos: 2
    # 限制文件变更并发数
    max-file-changes: 100

  # 本地待分析仓库路径数组
  local-repository-path:
    repos:
      - path: D:\ai-by-training
        remote: origin

      - path: E:\cJSON
        remote: origin

      - path: D:\markitdown
        remote: origin

      - path: E:\redis
        remote: origin

      - path: E:\jdk
        remote: origin

      - path: E:\kafka
        remote: origin

  # 分析记录邮件发送限流配置
  email-send-concurrent:
    # 最多同时处理的收件人数量
    max-recipients: 2
    # 发送邮件前需要延迟的时间
    each-send-delay: 100ms

  # Git 命令执行器配置参数
  git-command-runner:
    # 进程最大等待时间（单位：秒）
    process-max-wait-time: 1000
    # 异步读取的缓冲区大小（单位：字节）
    async-buffer-size: 65536
    retry:
      max-attempts: 3
      min-backoff: 1s
      max-backoff: 3s
      jitter-factor: 0.5

  # 是否启用本邮件发送器依赖？（默认启用）
  reactive-email-sender:
    enabled: true
    smtp-host: smtp.qq.com # 提供 SMTP 服务的运营商主机名
    smtp-port: 465         # SMTP 端口号
    backoff:
      max-attempt-times: 5
      start-backoff-interval: 2 # 指数退避起始时间间隔（单位：秒，默认为 1）
      max-backoff-interval: 5   # 指数退避封顶时间间隔（单位：秒，默认为 10）
    max-attachment-size: 8
    sender-email: 3191955858@qq.com # 发件人邮箱地址
    session-props:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          connectiontimeout: 5000

  # Thymeleaf 模板存放路径
  thymeleaf:
    prefix: templates/mail/